### ISSUE TITLE
Feature: Add typescript support

### ISSUE THREAD

**Issue by Manjit2003** [victorocna/awesome-react-starter#10]
Can you please add typescript support? It will be awesome. Thank you

**Comment by victorocna** [comment]
In the last couple of years I have avoided typescript because in my opinion it makes projects more complex and harder to read and understand without having many advantages that I personally find attractive. However, you can make a PR with typescript support or point me in the right direction of adding typescript in this project.

Thanks and hope to hear from you soon!
